# Generated by Django 2.2 on 2020-07-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProcesoNomina', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nomina',
            table='nomina',
        ),
        migrations.AlterModelTable(
            name='prenomina',
            table='pre_nomina',
        ),
    ]
