# Generated by Django 2.2 on 2020-07-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConceptoPago', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementopago',
            name='formula',
        ),
    ]
