# Generated by Django 2.2 on 2020-07-06 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('codigo_cargo', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Codigo Del Cargo')),
                ('cargo', models.CharField(max_length=50, null=True, verbose_name='Nombre del Cargo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion del Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['cargo'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigo_departamento', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Codigo Del Departamento')),
                ('descripcion', models.CharField(max_length=50, null=True, verbose_name='Descripcion')),
                ('cantidad_empleado', models.IntegerField(blank=True, null=True, verbose_name='Cantidad De Empleados')),
                ('presupuesto', models.FloatField(blank=True, null=True, verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['codigo_departamento', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('codigo_empleado', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cedula', models.IntegerField(blank=True, null=True, verbose_name='Cedula')),
                ('apellido', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('nombre', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre')),
                ('segundo_apellido', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Apellido')),
                ('sueldo', models.FloatField(blank=True, null=True, verbose_name='Sueldo Empleado')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso')),
                ('fecha_update', models.DateField(auto_now=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('edad', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefono')),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('ninguno', 'Prefiero No Responder')], max_length=50, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empleados')),
                ('status_trabajador', models.CharField(choices=[('trabajando', 'Trabajando'), ('nuevo_ingreso', 'Nuevo Ingreso')], default='Trabajando', max_length=30, verbose_name='Estado De La Persona')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('codigo_empresa', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50, null=True, verbose_name='Nombre de la Empresa')),
                ('rif', models.CharField(max_length=10)),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de Creacion de Empresa')),
                ('ceo', models.CharField(max_length=50, verbose_name='Fundador de la Empresa')),
                ('cantidad_empleado', models.PositiveIntegerField(verbose_name='Cantidad de Empleados')),
                ('proposito', models.TextField(verbose_name='Proposito de la Empresa')),
                ('fecha_update', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'organizacion',
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('codigo_escala', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Codigo De Escala')),
                ('escala', models.CharField(choices=[('1', 'Escala Nivel I'), ('2', 'Escala Nivel II'), ('3', 'Escala Nivel III'), ('4', 'Escala Nivel IV')], max_length=20, verbose_name='Nombre Escala')),
                ('grado', models.IntegerField(verbose_name='Grado')),
                ('paso', models.IntegerField(verbose_name='Paso')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Sueldo Base')),
                ('porcentaje', models.BooleanField(blank=True, default=0, null=True, verbose_name='Porcentaje')),
            ],
            options={
                'verbose_name': 'Escala de Sueldo',
                'verbose_name_plural': 'Escala de Sueldos',
                'ordering': ['escala'],
                'unique_together': {('escala', 'grado', 'paso')},
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('codigo_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trabajando', 'Trabajando'), ('desempleado', 'Desempleado'), ('ingresado', 'Ingresado')], default='desempleado', max_length=30, verbose_name='Estado De La Persona')),
                ('cedula', models.IntegerField(blank=True, null=True, verbose_name='Cedula')),
                ('apellido', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('nombre', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre')),
                ('segundo_apellido', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Apellido')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('edad', models.IntegerField(blank=True, null=True, verbose_name='Edad')),
                ('ocupacion_actual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Ocupacion Actual')),
                ('cargo_optar', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cargo a Optar')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefono')),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('ninguno', 'Prefiero No Responder')], max_length=50, null=True)),
                ('fecha_ingreso', models.DateField(auto_now=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empleados')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Solicitud De Ingreso',
                'verbose_name_plural': 'Solicitudes De Ingresos',
            },
        ),
        migrations.CreateModel(
            name='Rac',
            fields=[
                ('codigo_rac', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Codigo Puesto')),
                ('compensacion', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('cargo_ocupado', models.BooleanField(default=False)),
                ('codigo_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecursosHumanos.Cargo', verbose_name='Cargo')),
                ('codigo_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecursosHumanos.Departamento', verbose_name='Departamento')),
                ('codigo_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecursosHumanos.Empresa', verbose_name='Empresa')),
                ('codigo_escala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecursosHumanos.Escala')),
            ],
            options={
                'verbose_name': 'Puesto de Trabajo',
                'verbose_name_plural': 'Puestos de Trabajos',
                'ordering': ['codigo_rac', 'codigo_departamento'],
            },
        ),
        migrations.CreateModel(
            name='FamiliaEmpleado',
            fields=[
                ('codigo_familia', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.IntegerField(blank=True, null=True, verbose_name='Cedula')),
                ('apellido', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('nombre', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre')),
                ('segundo_apellido', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Apellido')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecursosHumanos.Empleado')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familiares',
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('codigo_familia', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.IntegerField(blank=True, null=True, verbose_name='Cedula')),
                ('apellido', models.CharField(max_length=30, verbose_name='Primer Apellido')),
                ('nombre', models.CharField(max_length=30, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Nombre')),
                ('segundo_apellido', models.CharField(blank=True, max_length=30, null=True, verbose_name='Segundo Apellido')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecursosHumanos.Persona')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familiares',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='codigo_rac',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecursosHumanos.Rac'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='codigo_solicitud',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecursosHumanos.Persona', verbose_name='Solicitud Empleado'),
        ),
        migrations.CreateModel(
            name='EducacionEmpleado',
            fields=[
                ('codigo_educ', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo Obtenido')),
                ('finalizado', models.BooleanField()),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha De Inicio Del Curso')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha De Obtencion Del Titulo')),
                ('aptitudes', models.CharField(max_length=50, verbose_name='Aptitud o Habilidad Obtenida')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecursosHumanos.Empleado')),
            ],
            options={
                'verbose_name': 'Nivel Educativo',
                'verbose_name_plural': 'Educacion',
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('codigo_educacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo Obtenido')),
                ('finalizado', models.BooleanField()),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha De Inicio Del Curso')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha De Obtencion Del Titulo')),
                ('aptitudes', models.CharField(max_length=50, verbose_name='Aptitud o Habilidad Obtenida')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecursosHumanos.Persona')),
            ],
            options={
                'verbose_name': 'Nivel Educativo',
                'verbose_name_plural': 'Educacion',
            },
        ),
        migrations.CreateModel(
            name='PersonaSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Informacion de Solicitud',
                'verbose_name_plural': 'Informacion de Solicitudes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('RecursosHumanos.persona',),
        ),
    ]
