# Generated by Django 2.2 on 2020-07-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecursosHumanos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rac',
            name='codigo_empresa',
        ),
    ]
