# Generated by Django 2.2 on 2020-07-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecursosHumanos', '0002_remove_rac_codigo_empresa'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cargo',
            table='cargo',
        ),
        migrations.AlterModelTable(
            name='departamento',
            table='departamento',
        ),
        migrations.AlterModelTable(
            name='educacion',
            table='educacion_candidato',
        ),
        migrations.AlterModelTable(
            name='educacionempleado',
            table='educacion_empleado',
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='empleado',
        ),
        migrations.AlterModelTable(
            name='escala',
            table='escala',
        ),
        migrations.AlterModelTable(
            name='familia',
            table='familia_candidato',
        ),
        migrations.AlterModelTable(
            name='familiaempleado',
            table='familia_empleado',
        ),
        migrations.AlterModelTable(
            name='persona',
            table='candidato',
        ),
        migrations.AlterModelTable(
            name='rac',
            table='rac',
        ),
    ]
