# Generated by Django 2.2 on 2020-07-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecursosHumanos', '0003_auto_20200706_0948'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='educacion',
            table='educacion__candidato',
        ),
        migrations.AlterModelTable(
            name='escala',
            table='escala_sueldo',
        ),
        migrations.AlterModelTable(
            name='familia',
            table='familia__candidato',
        ),
    ]
